$(function () {
    /* Mutil Language */
    var lang = localStorage.getItem('lang') || 'en';

    changeLanguage(lang);

})
function changeLanguage(lang) {
    if (lang == null || lang == '') lang = 'vi'
    var base_url = window.location.origin;
    if (lang == "en") {
        $(".icon-lang").attr('src', base_url + "/Content/assets/img/united-states.png");
        $(".text-lang").text("Tiếng Anh")
    } else if (lang == "vi") {
        $(".icon-lang").attr('src', base_url + "/Content/assets/img/vietnam.png");
        $(".text-lang").text("Tiếng Việt")
    } else if (lang == "ja") {
        $(".icon-lang").attr('src', base_url + "/Content/assets/img/japan.png");
        $(".text-lang").text("Tiếng Nhật")
    } else {
        $(".icon-lang").attr('src', base_url + "/Content/assets/img/united-states.png");
        $(".text-lang").text("Tiếng Anh")
    }

    //$.get("/Content/Json/lang.json", function (dt) {
    $(".lang").each(function (index, element) {
        $(this).text(arrLang[lang][$(this).attr("key")]);
        $(this).attr("placeholder", arrLang[lang][$(this).attr("key")]);
    });
    //});
}
$(".translate").click(function () {
    var lang = $(this).attr("id");
    localStorage.setItem('lang', lang);
    changeLanguage(lang);

});
var arrLang = {
    "en": {
        "Home": "Home",
        "Summary": "Summary",
        "Search-for": "Search for...",
        "Username": "Username",
        "create-request": "Create New Request",
        "send-to-me": "Waiting For Approval",
        "my-request": "My Request",
        "cancel-request": "Reject A Request",
        "finish-request": "Finish Request",
        "list-request": "REQUEST LIST",
        "all": "All",
        "in-turn": "Done",
        "overdue": "Not Yet",
        "title-supply-req": "Supply Request",
        "state": "State",
        "waitting": "Waiting For Approval",
        "accept": "Accept",
        "reject": "Reject",
        "delete": "Delete",
        "req-info": "Request Info",
        "code": "Code",
        "bc-dept": "BC Dept",
        "creator": "Creator",
        "date-create": "Create Time",
        "issus-date": "Issue Date",
        "dept": "Dept",
        "type-supply": "Type Supply",
        "staff_code": "Staff Code:",
        "table-no": "No",
        "table-code": "Staff Code",
        "table-item-name": "Item Name",
        "table-desc": "Description",
        "table-vendor": "Vendor",
        "table-unit-price": "Unit Price",
        "table-qty": "Qty",
        "table-unit": "Unit",
        "table-unit-detail": "(kg•pcs)",
        "table-amount": "Amount",
        "table-amount-detail": "(USD or VND)",
        "table-owner-of-item": "Owner of Item",
        "table-owner-of-item-detail": "U→UMC, C→Customer",
        "table-cost-center": "Cost Center",
        "table-cost-center-detail": "AI/SMT/FAT/ Other/Office",
        "table-account": "Account",
        "table-asset-no": "Asset No",
        "table-total": "Total",
        "more-info": "**More Infomation**",
        "req-delivery-date": "- Request Delivery Date: ",
        "note": "- Remark: ",
        "round-robin": "- Round robin: ",
        "yes": "YES",
        "no": "NO",
        "req-checkout": "Có yêu cầu khách hàng thanh toán : Có / Không",
        "attach": "**File Attach**",
        "quote_attach": "**File Quote Attach**",
        "main-action": "Main Action",
        "apply": "Applicant",
        "dept-manager": " Dept Manager",
        "asset-center": " Asset Center",
        "factory-manager": "Factory Manager",
        "general-director": "General Director",
        "purchasing-dept": "Purchasing Dept",
        "purchasing-dept-detail": "Approved by",
        "Receive_check": "Recieve Check",
        "applicant": "Applicant",
        "asset-center-recive-check": "Asset Center",
        "comment": "Comment",
        "send": "Send",
        "name": "Name",
        "add-row": "Add row",
        "add-column":"Add column",
        "cancel": "Cancel",
        "create": "Create",
        "return": "Back to",
        "type_form": "Choose Type Form",
        "save_change": "Save changes",
        "title": "UMC FORM REQUEST",
        "select_dept": "Select Dept",
        "reconfirm": "Reconfirm",
        "lca_request": "GIẤY YÊU CẦU PHÒNG CƠ KHÍ",
        "monthly": "Monthly",
        "daily": "Daily",
        "Người yêu cầu": "Người yêu cầu",
        "Phê duyệt": "Phê duyệt",
        "reaccept": "Re-accept",
        "need_enter_english": "Please add comment by English or Japanese",
        "dept_manager": "Dept Manager",
        "edit_quote": "Save Changes",
        "follow-request": "Following",
        "title_request": "Title",
        "target-date": "Ngày Mong Muốn",
        "request-date": "Ngày Yêu Cầu",
        "request_dept": "Bộ Phận Yêu Cầu",
        "target-supply": "Mục đích yêu cầu",
        "type-jip-supply": "Phân loại Jig",
        "increase_productivity": "Tăng năng suất",
        "new_model": "Model mới",
        "incre_prod": "Do tăng sản lượng",
        "quantity": "Cải tiến C/Lượng",
        "5s": "5S改善",
        "ngjig": "JIG bị mòn/NG",
        "uoc_luong_hieu_qua": "Ước lượng hiệu quả khi áp dụng mới",
        "reduce_staff": "Cắt giảm người",
        "hieu_qua_cai_tien_chat_luong": "Hiệu quả cải tiến chất lượng",
        "tiet_kiem_chi_phi": "Tiết kiệm chi phí",
        "noi_dung_loi": "Nội dung Lỗi:",
        "ty_le_loi": "Tỷ lệ lỗi hiện tại",
        "hieu_qua_cai_tien": "Hiệu quả cải tiến",
        "chi_tra": "Chi Trả",
        "Customer": "Khách hàng",
        "doi_tuong_ap_dung": "1.■Đối tượng áp dụng:",
        "req-dept": "① Bộ phận yêu cầu",
        "lca_bao_gia": "② LCA 「見積もり] /Báo giá, Leadtime",
        "received-date": "Ngày nhận:",
        "table-item-req": "Hạng mục yêu cầu",
        "title-lca-req": "GIẤY YÊU CẦU PHÒNG CƠ KHÍ ",
        "form_bieu": "Form List",
        "count_subscriber": "Count subscriber",
        "subscribe-date": "Subscribe date",
        "reason-leave": "Reason for leave",
        "special-leave": "Special leave",
        "total-date": "Total date",
        "frmpaidleave_title": "GIẤY ĐĂNG KÝ NGHỈ CÓ LƯƠNG",
        "request_dept_sub": "Bộ phận đăng ký",
        "frmunpaidleave_title": "GIẤY ĐĂNG KÝ NGHỈ KHÔNG LƯƠNG",
        "request_date_sub": "Ngày đăng ký",
        "group_leader": "Leader",
        "my-approve":"Approved"
    },
    "vi": {
        "Home": "TRANG CHỦ",
        "Summary": "Tổng kết",
        "Search-for": "Tìm kiếm...",
        "Username": "Tên đăng nhập",
        "create-request": "Tạo Đề Xuất Mới",
        "send-to-me": "Cần phê duyệt",
        "my-request": "Tôi Gửi Đi",
        "cancel-request": "Bị Từ Chối",
        "finish-request": "Đã Hoàn Thành",
        "following": "Đang Theo Dõi",
        "list-request": "DANH SÁCH ĐỀ XUẤT",
        "all": "Tất Cả",
        "in-turn": "Đã Làm",
        "overdue": "Chưa Làm",
        "title-supply-req": "Yêu Cầu Cung Cấp",
        "state": "Trạng thái",
        "waitting": "Đang chờ duyệt",
        "accept": "Chấp thuận",
        "reject": "Từ chối",
        "delete": "Xóa",
        "req-info": "Thông Tin Đề Xuất",
        "code": "Mã Đề Xuất: ",
        "creator": "Người Tạo",
        "date-create": "Thời Gian Tạo",
        "issus-date": "Ngày Phát Hành",
        "dept": "Bộ Phận",
        "type-supply": "Loại Yêu Cầu",
        "staff_code": "Mã Nhân Viên:",
        "table-no": "STT",
        "table-code": "Mã Số",
        "table-item-name": "Tên Hàng",
        "table-desc": "Quy Cách",
        "table-vendor": "Nhà Cung Cấp",
        "table-unit-price": "Đơn Giá",
        "table-qty": "Số Lượng",
        "table-unit": "Đơn Vị ",
        "table-unit-detail": "(kg*pcs)",
        "table-amount": "Số Tiền",
        "table-amount-detail": "(USD or VND)",
        "table-owner-of-item": "Owner of Item",
        "table-owner-of-item-detail": "U→UMC, C→Customer",
        "table-cost-center": "Cost Center",
        "table-cost-center-detail": "AI/SMT/FAT/ Other/Office",
        "table-account": "Tài Khoản",
        "table-asset-no": "Số Tài Sản",
        "table-total": "Tổng Số",
        "more-info": "**Thông Tin Thêm**",
        "req-delivery-date": "- Ngày yêu cầu giao hàng: ",
        "note": "- Ghi chú: ",
        "round-robin": "- Round robin: ",
        "yes": "Có",
        "no": "Không",
        "req-checkout": "Có yêu cầu khách hàng thanh toán : Có/ Không",
        "attach": "**File đính kèm**",
        "quote_attach": "**File báo giá đính kèm**",
        "main-action": "hoạt động chính",
        "apply": "Người Đề Xuất",
        "dept-manager": "Trưởng Phòng",
        "asset-center": "Qly Tài Sản",
        "factory-manager": "Giám Đốc Xưởng",
        "general-director": "Tổng Giám Đốc",
        "purchasing-dept": "Phòng Mua Hàng",
        "purchasing-dept-detail": "Người Duyệt",
        "Receive_check": "Recieve Check",
        "applicant": "Applicant",
        "asset-center-recive-check": "Asset Center",
        "bc-dept": "Phòng BC",
        "comment": "Thảo Luận",
        "send": "Gửi",
        "name": "Họ Tên",
        "add-row": "Thêm dòng",
        "cancel": "Hủy",
        "create": "Đề xuất",
        "return": "Quay lại bước",
        "type_form": "Chọn Mẫu Form",
        "save_change": "Lưu thay đổi",
        "title": "UMC FORM REQUEST",
        "select_dept": "Chọn Phòng Ban",
        "reconfirm": "Xác nhận lại",
        "lca_request": "GIẤY YÊU CẦU PHÒNG CƠ KHÍ",
        "target-date": "Ngày Mong Muốn",
        "request-date": "Ngày Yêu Cầu",
        "request_dept": "Bộ Phận Yêu Cầu",
        "target-supply": "Mục đích yêu cầu",
        "type-jip-supply": "Phân loại Jig",
        "increase_productivity": "Tăng năng suất",
        "new_model": "Model mới",
        "incre_prod": "Do tăng sản lượng",
        "quantity": "Cải tiến C/Lượng",
        "5s": "5S改善",
        "ngjig": "JIG bị mòn/NG",
        "uoc_luong_hieu_qua": "Ước lượng hiệu quả khi áp dụng mới",
        "reduce_staff": "Cắt giảm người",
        "hieu_qua_cai_tien_chat_luong": "Hiệu quả cải tiến chất lượng",
        "tiet_kiem_chi_phi": "Tiết kiệm chi phí",
        "noi_dung_loi": "Nội dung Lỗi:",
        "ty_le_loi": "Tỷ lệ lỗi hiện tại",
        "hieu_qua_cai_tien": "Hiệu quả cải tiến",
        "chi_tra": "Chi Trả",
        "Customer": "Khách hàng",
        "doi_tuong_ap_dung": "1.■Đối tượng áp dụng:",
        "req-dept": "① Bộ phận yêu cầu",
        "lca_bao_gia": "② LCA 「見積もり] /Báo giá, Leadtime",
        "received-date": "Ngày nhận:",
        "table-item-req": "Hạng mục yêu cầu",
        "title-lca-req": "GIẤY YÊU CẦU PHÒNG CƠ KHÍ ",
        "Người yêu cầu": "Người yêu cầu",
        "Phê duyệt": "Phê duyệt",
        "monthly": "Ngày",
        "daily": "Tháng",
        "reaccept": "Xác nhận lại",
        "need_enter_english": "Please add comment by English or Japanese",
        "dept_manager": "Trưởng phòng",
        "edit_quote": "Sửa Báo Giá",
        "follow-request": "Đang theo dõi",
        "title_request": "Tiêu đề",
        "form_bieu": "Form Biểu",
        "count_subscriber": "Số người đăng ký",
        "subscribe-date": "Ngày đăng ký nghỉ",
        "reason-leave": "Lý do nghỉ",
        "special-leave": "Nghỉ đặc biệt",
        "total-date": "Tổng ngày",
        "frmpaidleave_title": "GIẤY ĐĂNG KÝ NGHỈ CÓ LƯƠNG",
        "request_dept_sub": "Bộ phận đăng ký",
        "frmunpaidleave_title": "GIẤY ĐĂNG KÝ NGHỈ KHÔNG LƯƠNG",
        "request_date_sub": "Ngày đăng ký",
        "group_leader": "Trưởng Nhóm",
        "my-approve": "Đã phê duyệt"
    },
    "ja": {
        "reaccept": "Re-accept",
        "lca_request": "冶工具　加工依頼書",
        "target-date": "渡し希望日",
        "request-date": "依頼日",
        "request_dept": "依頼部門",
        "target-supply": "目的",
        "type-jip-supply": "治具の分類",
        "increase_productivity": "生産性UP",
        "new_model": "New Model",
        "incre_prod": "増産",
        "quantity": "品質改善",
        "5s": "5S改善",
        "ngjig": "NG JIGチェンジ",
        "uoc_luong_hieu_qua": "効果",
        "reduce_staff": "活人効果",
        "hieu_qua_cai_tien_chat_luong": "品質改善効果",
        "tiet_kiem_chi_phi": "金効果",
        "noi_dung_loi": "不良内容",
        "ty_le_loi": "現在不良率",
        "hieu_qua_cai_tien": "改善効果",
        "chi_tra": "支払",
        "Customer": "顧客",
        "doi_tuong_ap_dung": " 1.■利用",
        "req-dept": "① 依頼部門",
        "lca_bao_gia": "② 見積もり作成⇒Jig作成実施可能承認",
        "received-date": "受付日:",
        "table-item-req": "依頼項目",
        "table-qty": "数量",
        "title-lca-req": " 冶工具　加工依頼書",
        "Người yêu cầu": "担当",
        "Phê duyệt": "承認",
        "monthly": "月",
        "daily": "日",
        "need_enter_english": "Please add comment by English or Japanese",
        "dept_manager": "部長",
        "edit_quote": "Save Changes",
        "follow-request": "Following",
        "title_request": "Title",
        "form_bieu": "Form List",
        "all": "All",
        "in-turn": "Done",
        "overdue": "Not Yet",
        "attach": "**File Attach**",
        "quote_attach": "**File Quote Attach**",
        "frmpaidleave_title": "慶弔休暇、リフレッシュ休暇",
        "request_dept_sub": "部署",
        "frmunpaidleave_title": "無給休暇届 ",
        "request_date_sub": "申請日",
        "group_leader": "リーダー",
        "count_subscriber": "人数",
        "table-code": "コード",
        "subscribe-date": "取得日",
        "reason-leave": "理由",
        "special-leave": "慶弔休暇",
        "name": "氏名",
        "total-date": "日間",
        "cancel-request": "キャンセル",
        "my-approve": "Approved",
        "delete": "Delete",
    }
};
